const STORAGE_KEY = "phd-intelligence-v1";
const clone = x => JSON.parse(JSON.stringify(x));
let state = load();
let currentView = "dashboard";
let query = "";

function mergeAuto(saved){ if(!saved.meta.strategyVersion){ saved.profile.gpa=3.3; saved.profile.target="US CS / AI PhD · Multimodal + Robotics"; saved.profile.focus=["Multimodal AI","Robotics / Embodied AI","Video & Spatial Reasoning","Benchmark & Data"]; saved.summerResearch=clone(window.SEED_DATA.summerResearch||[]); saved.meta.strategyVersion=2; } const modules=["papers","publications","sopDocuments","recommenders","recommendations","contactRecords","tests","cvItems","interviews","offers","costs","labMembers","communityClaims","facultyTimeline","notes","tags","deadlines","aiTraces","verificationRecords"]; for(const key of modules) if(!Array.isArray(saved[key])) saved[key]=clone(window.SEED_DATA[key]||[]); saved.meta.schemaVersion=3; if(!saved.fitWeights) saved.fitWeights=clone(window.SEED_DATA.fitWeights); if(!saved.schoolPriorityWeights) saved.schoolPriorityWeights=clone(window.SEED_DATA.schoolPriorityWeights); if(!Array.isArray(saved.schoolPriorities)) saved.schoolPriorities=clone(window.SEED_DATA.schoolPriorities||[]); const auto=window.AUTO_DATA||{}; for(const key of ["programs","faculty","sources"]){ const seen=new Set((saved[key]||[]).map(x=>x.id)); for(const item of auto[key]||[]) if(!seen.has(item.id)) (saved[key]||(saved[key]=[])).push(clone(item)); } return saved; }
function load(){ try { return mergeAuto(JSON.parse(localStorage.getItem(STORAGE_KEY)) || clone(window.SEED_DATA)); } catch { return clone(window.SEED_DATA); } }
function persist(action, entity, detail){
  if(action) state.history.unshift({id:uid("h"),at:new Date().toISOString(),action,entity,detail});
  localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  if(action) toast("已保存，并记录到修改历史");
}
function uid(prefix){ return prefix + Date.now().toString(36) + Math.random().toString(36).slice(2,5); }
const esc = s => String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const program = id => state.programs.find(x=>x.id===id);
const project = id => state.projects.find(x=>x.id===id);
const faculty = id => state.faculty.find(x=>x.id===id);
const fmt = d => d ? new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"short",day:"numeric"}).format(new Date(d+(/T/.test(d)?"":"T00:00:00"))) : "—";
const daysTo = d => Math.ceil((new Date(d+"T00:00:00")-new Date())/86400000);
const statusClass = s => /high|confirmed|submitted|offer|ready|active/i.test(s)?"green":/unknown|research|consider|prepar|likely/i.test(s)?"amber":/reject|outdated|not_/i.test(s)?"red":"blue";
const nav = [
  ["Core",[["dashboard","⌂","Dashboard"],["programs","▦","Programs"],["faculty","♙","Faculty"],["matrix","⊞","Research Match"]]],
  ["My Research",[["research","◈","Projects"],["papers","▤","Paper Tracking"],["publications","◫","Publications"],["cv","▧","CV Data"]]],
  ["Applications",[["shortlist","☆","School List"],["applications","✓","Application Tracker"],["sop","¶","SOP Workspace"],["recommendations","♢","Recommendations"],["contact_workspace","✉","Professor Contact"]]],
  ["Planning",[["summer","☀","Summer Research"],["calendar","□","Calendar"],["tests","A","Tests"],["costs","$","Costs"],["sources","◎","Sources & Verification"],["notes","✎","Notes"]]],
  ["Faculty Intel",[["labnetwork","♧","Lab & Tsinghua"],["community","◉","Community Claims"],["faculty_timeline","↝","Evidence Timeline"]]],
  ["Results",[["interviews","◇","Interviews"],["offers","◆","Offers"]]],
  ["System",[["history","↻","Change History"],["settings","⚙","Settings & Data"]]]
];

function shell(){
  document.documentElement.dataset.theme=localStorage.getItem("theme")||"light";
  document.getElementById("app").innerHTML=`<div class="app-shell"><aside class="sidebar" id="sidebar">
    <div class="brand"><div class="brand-mark">AI</div><div><strong>Application Intel</strong><span>${esc(state.profile.cycle)} · CS PhD</span></div></div>
    ${nav.map(([section,items])=>`<div class="nav-section">${section}</div>${items.map(([id,icon,label])=>`<button class="nav-item ${currentView===id?"active":""}" data-view="${id}"><span class="nav-icon">${icon}</span>${label}</button>`).join("")}`).join("")}
    <div class="sidebar-foot">Local-first workspace<br><span class="update-dot"></span>所有改动自动保存在此浏览器</div>
  </aside><main class="main"><header class="topbar"><button class="icon-btn mobile-menu" id="menu">☰</button><div class="search"><input id="global-search" value="${esc(query)}" placeholder="搜索学校、教授、项目或研究方向…"></div><div class="top-actions"><button class="icon-btn" id="theme" title="切换主题">◐</button><button class="btn" id="export">导出备份</button></div></header><div class="content" id="content">${renderView()}</div></main></div>`;
  bind();
}
function head(kicker,title,sub,action=""){return `<div class="page-head"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${sub}</p></div>${action?`<div class="head-actions">${action}</div>`:""}</div>`}
function stat(label,value,hint){return `<div class="stat"><div class="label">${label}</div><div class="value">${value}</div><div class="hint">${hint}</div></div>`}
function renderView(){if(query.trim()&&window.renderGlobalSearch)return window.renderGlobalSearch(query.trim());const extended=window.extendedViews?.[currentView];return extended?extended():({dashboard,programs,faculty:facultyView,matrix,research,papers,shortlist,applications,contacts,summer,calendar,sources,history,settings}[currentView]||dashboard)()}

function dashboard(){
  const high=state.faculty.filter(f=>bestScore(f.id)>=85).length, submitted=state.applications.filter(a=>a.status==="Submitted").length;
  const earliest=[...state.programs].sort((a,b)=>a.deadline.localeCompare(b.deadline))[0];
  const queue=state.faculty.filter(f=>bestScore(f.id)>=85&&(/unknown/.test(f.recruiting)||f.completion<75)).slice(0,5);
  const stages=["Researching","Shortlisted","Preparing","Submitted","Interview","Offer"];
  return `${head("Application command center",`${esc(state.profile.cycle)} CS PhD Application`,`Multimodal + Robotics first · GPA-aware · evidence backed`)}
  <div class="grid stats">${stat("Total Programs",state.programs.length,"5 programs seeded")}${stat("Faculty Tracked",state.faculty.length,`${high} high-fit faculty`)}${stat("Applications",state.applications.length,`${submitted} submitted`)}${stat("Professor Contacts",state.faculty.filter(f=>!["not_planned","planning"].includes(f.contact)).length,`${state.faculty.filter(f=>f.contact==="replied").length} replies`)}${stat("Interviews / Offers","0 / 0","Application funnel")}</div>
  <div class="panel" style="margin-bottom:16px"><div class="countdown"><div><span>Earliest deadline</span><strong>${earliest?fmt(earliest.deadline):"—"}</strong><span>${earliest?esc(earliest.school):"No deadline"}</span></div><div><span>Days remaining</span><strong>${earliest?Math.max(0,daysTo(earliest.deadline)):"—"}</strong><span>基于示例截止日期</span></div><div><span>Information health</span><strong>${state.sources.filter(s=>s.status==="official_confirmed").length}/${state.sources.length}</strong><span>officially confirmed</span></div></div></div>
  <div class="grid two-col"><div class="grid"><section class="panel"><div class="panel-head"><h2>Application funnel</h2><span>Current pipeline</span></div><div class="panel-body"><div class="funnel">${stages.map(s=>`<div class="funnel-step"><b>${state.applications.filter(a=>a.status===s).length}</b><span>${s}</span></div>`).join("")}</div></div></section>
  <section class="panel"><div class="panel-head"><h2>Faculty research queue</h2><span>High fit, incomplete evidence</span></div><div class="panel-body">${queue.length?queue.map(f=>`<div class="queue-item"><div class="queue-top"><div><strong>${esc(f.name)}</strong> <span class="status ${statusClass(f.consideration)}">${esc(f.consideration.replaceAll("_"," "))}</span></div><span class="score">${bestScore(f.id)}</span></div><p>${/unknown/.test(f.recruiting)?"Recruiting verification missing · ":""}${f.completion<75?`Research completion ${f.completion}%`:""}</p><div class="progress"><i style="width:${f.completion}%"></i></div></div>`).join(""):"<div class='empty'>Queue clear</div>"}</div></section></div>
  <section class="panel"><div class="panel-head"><h2>Next actions</h2><button class="btn subtle" data-add="task">+ Task</button></div><div class="panel-body">${state.tasks.map(t=>`<label class="task"><input type="checkbox" data-task="${t.id}" ${t.done?"checked":""}><div class="task-info"><div class="task-title">${esc(t.title)}</div><div class="task-meta">${esc(t.type)} · ${fmt(t.due)}</div></div></label>`).join("")}</div></section></div>`;
}
function programs(){
 const rows=state.programs.filter(p=>hay(p).includes(query.toLowerCase()));
 return `${head("School → Program","Program Database","Cycle-specific requirements, funding, admission model and evidence.",`<button class="btn primary" data-add="program">+ Add program</button>`)}<div class="toolbar"><select id="tier-filter"><option value="">All tiers</option>${["Dream","Reach","Target","Lower Risk"].map(x=>`<option>${x}</option>`).join("")}</select><span class="tag">${rows.length} programs</span></div><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Program</th><th>Tier / Priority</th><th>Deadline</th><th>Requirements</th><th>Funding</th><th>Advisor model</th><th>Faculty depth</th><th></th></tr></thead><tbody>${rows.map(p=>`<tr data-tier="${p.tier}"><td><div class="school-name">${esc(p.school)}</div><div class="subtext">${esc(p.department)} · ${esc(p.city)}, ${esc(p.state)}</div></td><td><span class="status ${statusClass(p.tier)}">${p.tier}</span><div class="subtext">Strategy ${schoolScore(p)} · GPA risk ${gpaRisk(p)}</div></td><td>${fmt(p.deadline)}<div class="subtext">${daysTo(p.deadline)} days</div></td><td>GRE: ${esc(p.gre)}<div class="subtext">TOEFL ${esc(p.toefl)} · $${p.fee}</div></td><td><span class="status green">${esc(p.funding)}</span></td><td>${esc(p.model)}</td><td><div class="risk">${[1,2,3].map(i=>`<i class="${i<=p.facultyCount?"on":""}"></i>`).join("")}</div><div class="subtext">${p.facultyCount} tracked</div></td><td><button class="btn subtle" data-edit-program="${p.id}">Edit</button></td></tr>`).join("")}</tbody></table></div></section>`;
}
function facultyView(){
 const rows=state.faculty.filter(f=>hay(f).includes(query.toLowerCase()));
 return `${head("Faculty intelligence","Faculty Database","Fit, evidence depth, lab network, recruiting and decision workflow.",`<button class="btn primary" data-add="faculty">+ Add faculty</button>`)}<div class="toolbar"><select id="faculty-filter"><option value="">All consideration</option>${["not_reviewed","researching","considering","high_priority","backup","not_considering"].map(x=>`<option value="${x}">${x.replaceAll("_"," ")}</option>`).join("")}</select><span class="tag">${rows.length} faculty</span></div><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Faculty</th><th>Research fit</th><th>Matched project</th><th>Recruiting</th><th>Tsinghua</th><th>Consideration</th><th>Research progress</th><th>Contact</th><th>Last checked</th></tr></thead><tbody>${rows.map(f=>{let m=bestMatch(f.id),p=program(f.programId);return `<tr data-consideration="${f.consideration}"><td><a class="faculty-name" href="#" data-faculty="${f.id}">${esc(f.name)}</a><div class="subtext">${esc(p?.school)} · ${esc(f.position)}</div></td><td><span class="score">${m?.score||0}</span><div class="score-bar"><i style="width:${m?.score||0}%"></i></div></td><td>${esc(project(m?.projectId)?.short||"—")}</td><td><span class="status ${statusClass(f.recruiting)}">${esc(f.recruiting.replaceAll("_"," "))}</span></td><td>${f.tsinghua?`<span class="status blue">${f.tsinghua} connection</span>`:"—"}</td><td><select class="quick-status" data-id="${f.id}">${["not_reviewed","researching","considering","high_priority","backup","contact_later","not_considering","archived"].map(s=>`<option ${s===f.consideration?"selected":""}>${s}</option>`).join("")}</select></td><td><div class="progress" style="width:90px"><i style="width:${f.completion}%"></i></div><div class="subtext">${f.completion}% complete</div></td><td>${esc(f.contact.replaceAll("_"," "))}</td><td>${fmt(f.lastChecked)}</td></tr>`}).join("")}</tbody></table></div></section>`;
}
function matrix(){return `${head("Faculty × Project","Research Match Matrix","Click a score to inspect dimension-level fit and a personalized research pitch.")}<section class="panel"><div class="table-wrap"><table class="data-table matrix"><thead><tr><th>Faculty</th>${state.projects.map(p=>`<th>${esc(p.short)}</th>`).join("")}<th>Best match</th></tr></thead><tbody>${state.faculty.map(f=>`<tr><td><div class="faculty-name">${esc(f.name)}</div><div class="subtext">${esc(program(f.programId)?.school)}</div></td>${state.projects.map(p=>{let m=state.matches.find(x=>x.facultyId===f.id&&x.projectId===p.id);let s=m?.score||0;return `<td><button class="matrix-score ${s>=85?"s-high":s>=65?"s-mid":"s-low"}" data-match="${f.id}:${p.id}">${s||"—"}</button></td>`}).join("")}<td>${esc(project(bestMatch(f.id)?.projectId)?.short||"—")}</td></tr>`).join("")}</tbody></table></div></section>`}
function research(){return `${head("Candidate profile","My Research","Editable research narrative and structured projects that feed faculty fit.",`<button class="btn" data-edit-profile="1">Edit profile</button><button class="btn primary" data-add="project">+ Add project</button>`)}<section class="panel" style="margin-bottom:16px"><div class="panel-body"><div class="eyebrow">${esc(state.profile.institution)} · ${esc(state.profile.degree)} · GPA ${esc(state.profile.gpa||"—")}</div><h2 style="font:700 20px Manrope;margin:8px 0">${esc(state.profile.target)}</h2><p style="color:var(--muted);max-width:850px">${esc(state.profile.statement)}</p><div class="keywords">${state.profile.focus.map(k=>`<span class="tag">${esc(k)}</span>`).join("")}</div></div></section><div class="cards">${state.projects.map(p=>`<article class="panel project-card"><span class="status ${statusClass(p.status)}">${esc(p.status)}</span><h3>${esc(p.name)}</h3><div class="eyebrow">${esc(p.area)}</div><p><strong>Problem</strong><br>${esc(p.problem)}</p><p><strong>Method</strong><br>${esc(p.method)}</p><p><strong>My contribution</strong><br>${esc(p.contribution)}</p><div class="keywords">${p.keywords.slice(0,8).map(k=>`<span class="tag">${esc(k)}</span>`).join("")}</div><button class="btn subtle" style="margin-top:16px" data-edit-project="${p.id}">Edit project</button></article>`).join("")}</div>`}
function papers(){return `${head("Knowledge base","Papers & Publications","Reading intelligence is designed into the data model; add paper tracking in the next iteration.",`<button class="btn primary" onclick="alert('Paper CRUD is represented in prisma/schema.prisma and scheduled for Phase 3.')">+ Add paper</button>`)}<section class="panel"><div class="empty"><h3>No papers tracked yet</h3><p>Start from high-fit faculty and capture recent papers, relevance, gaps, and reading status.</p></div></section>`}
function shortlist(){return `${head("Decision support","My School List","Priority is driven by research depth, funding and program environment—not ranking alone.")}<div class="cards">${[...state.programs].sort((a,b)=>schoolScore(b)-schoolScore(a)).map(p=>{let fs=state.faculty.filter(f=>f.programId===p.id&&(f.position!=="Faculty candidate"||f.reviewStatus==="confirmed"));return `<article class="panel project-card"><div style="display:flex;justify-content:space-between"><span class="status ${statusClass(p.tier)}">${p.tier}</span><span class="score">${schoolScore(p)}</span></div><h3>${esc(p.school)}</h3><p>${esc(p.program)}</p><div class="detail-grid"><div><div class="subtext">Best faculty</div><strong>${esc(fs.sort((a,b)=>bestScore(b.id)-bestScore(a.id))[0]?.name||"—")}</strong></div><div><div class="subtext">Faculty depth</div><strong>${p.facultyCount>=3?"Healthy":p.facultyCount===2?"Moderate":"High risk"}</strong><div class="subtext">GPA risk: ${gpaRisk(p)}</div></div></div><p><strong>Why apply</strong><br>${fs.length?`${fs.length} tracked faculty; strongest fit ${Math.max(...fs.map(f=>bestScore(f.id)))}.`:"Faculty research needed."}</p><p><strong>Risk</strong><br>${p.facultyCount<2?"Only one matching faculty currently tracked.":"Maintain advisor backup and verify recruiting."}</p></article>`}).join("")}</div>`}
function applications(){return `${head("Execution","Application Tracker","Checklist progress, materials, deadlines and current funnel state.",`<button class="btn primary" data-add="application">+ Add application</button>`)}<section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Program</th><th>Status</th><th>Deadline</th><th>Progress</th><th>Completed tasks</th><th>Notes</th></tr></thead><tbody>${state.applications.map(a=>{let p=program(a.programId);return `<tr><td><div class="school-name">${esc(p?.school)}</div><div class="subtext">${esc(p?.program)}</div></td><td><select class="app-status" data-id="${a.id}">${["Considering","Researching","Shortlisted","Preparing","Ready","Submitted","Interview","Offer","Rejected","Withdrawn"].map(s=>`<option ${s===a.status?"selected":""}>${s}</option>`).join("")}</select></td><td>${fmt(a.deadline)}</td><td><div class="progress" style="width:120px"><i style="width:${a.progress}%"></i></div><div class="subtext">${a.progress}%</div></td><td>${a.tasks.map(t=>`<span class="tag">✓ ${esc(t)}</span>`).join(" ")}</td><td>${esc(a.notes)}</td></tr>`}).join("")}</tbody></table></div></section>`}
function contacts(){return `${head("Outreach","Professor Contact","Personalized contact status linked to research evidence and relevant projects.")}<section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Faculty</th><th>Best project</th><th>Fit</th><th>Contact status</th><th>Possible pitch</th></tr></thead><tbody>${state.faculty.filter(f=>f.consideration!=="not_considering").map(f=>{let m=bestMatch(f.id);return `<tr><td><div class="faculty-name">${esc(f.name)}</div><div class="subtext">${esc(program(f.programId)?.school)}</div></td><td>${esc(project(m?.projectId)?.name)}</td><td class="score">${m?.score}</td><td><select class="contact-status" data-id="${f.id}">${["not_planned","planning","drafted","sent","replied","follow_up","meeting","no_response"].map(s=>`<option ${s===f.contact?"selected":""}>${s}</option>`).join("")}</select></td><td>${esc(m?.pitch||"Research fit assessment needed")}</td></tr>`}).join("")}</tbody></table></div></section>`}
function summer(){let rows=state.summerResearch||[];return `${head("Research leverage","Summer Research","Prioritize multimodal and robotics opportunities that can strengthen research output, references and advisor relationships.","")}<div class="grid stats">${stat("Opportunities",rows.length,"Formal programs + direct lab routes")}${stat("High priority",rows.filter(x=>x.priority>=85).length,"Priority ≥ 85")}${stat("GPA context",state.profile.gpa||"3.3","Research evidence matters more")}${stat("Primary direction","Multimodal","with Robotics / Embodied AI")}${stat("Next deadline",fmt([...rows].sort((a,b)=>a.deadline.localeCompare(b.deadline))[0]?.deadline),"Verify before acting")}</div><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Opportunity</th><th>Priority</th><th>Type / eligibility</th><th>Deadline</th><th>Strategic fit</th><th>Verification</th></tr></thead><tbody>${rows.sort((a,b)=>b.priority-a.priority).map(x=>`<tr><td><a href="${esc(x.sourceUrl)}" target="_blank" rel="noopener" class="school-name">${esc(x.program)} ↗</a><div class="subtext">${esc(x.school)}</div></td><td><span class="score">${x.priority}</span></td><td>${esc(x.type)}<div class="subtext">${esc(x.eligibility)}</div></td><td>${fmt(x.deadline)}</td><td>${esc(x.fit)}<div class="subtext">${esc(x.value)}</div></td><td><span class="status ${statusClass(x.verification)}">${esc(x.verification.replaceAll("_"," "))}</span><div class="subtext">checked ${fmt(x.lastChecked)}</div></td></tr>`).join("")}</tbody></table></div></section>`}

function calendar(){let sorted=[...state.programs].sort((a,b)=>a.deadline.localeCompare(b.deadline));return `${head("Planning","Deadline Timeline","Application deadlines and tasks; dates remain marked as examples until officially verified.")}<div class="grid two-col"><section class="panel"><div class="panel-head"><h2>Application deadlines</h2><span>Chronological</span></div><div class="panel-body"><div class="timeline">${sorted.map(p=>`<div class="timeline-item"><strong>${fmt(p.deadline)} · ${esc(p.school)}</strong><p>${esc(p.program)} · <span class="status ${daysTo(p.deadline)<14?"red":"green"}">${daysTo(p.deadline)} days</span></p></div>`).join("")}</div></div></section><section class="panel"><div class="panel-head"><h2>Internal milestones</h2><span>${state.tasks.length} tasks</span></div><div class="panel-body">${state.tasks.map(t=>`<div class="task"><div class="task-info"><div class="task-title">${esc(t.title)}</div><div class="task-meta">${fmt(t.due)} · ${esc(t.type)}</div></div></div>`).join("")}</div></section></div>`}
function sources(){return `${head("Evidence layer","Sources & Verification","Official sources outrank community claims; volatile data never becomes fact without review.",`<button class="btn primary" data-add="source">+ Add source</button>`)}<section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Entity / claim</th><th>Source</th><th>Type</th><th>Last checked</th><th>Confidence</th><th>Verification</th><th>Evidence note</th></tr></thead><tbody>${state.sources.map(s=>`<tr><td class="school-name">${esc(s.entity)}</td><td><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.name)} ↗</a></td><td>${esc(s.type.replaceAll("_"," "))}</td><td>${fmt(s.lastChecked)}</td><td><span class="status ${statusClass(s.confidence)}">${s.confidence}</span></td><td><span class="status ${statusClass(s.status)}">${s.status.replaceAll("_"," ")}</span></td><td>${esc(s.claim)}</td></tr>`).join("")}</tbody></table></div></section>`}
function history(){return `${head("Audit trail","Change History","Every local edit is timestamped. Export a JSON backup to preserve or move the record.")}<section class="panel"><div class="panel-body"><div class="timeline">${state.history.map(h=>`<div class="timeline-item"><strong>${esc(h.action)} · ${esc(h.entity)}</strong><p>${new Date(h.at).toLocaleString("zh-CN")} · ${esc(h.detail)}</p></div>`).join("")}</div></div></section>`}
function settings(){return `${head("Local-first","Settings & Data","Your data stays in this browser unless you export it.")}<div class="grid three-col"><section class="panel project-card"><div class="eyebrow">Backup</div><h3>Export JSON</h3><p>Download every record, source and history entry as a portable snapshot.</p><button class="btn primary" id="export-settings">Download backup</button></section><section class="panel project-card"><div class="eyebrow">Restore</div><h3>Import JSON</h3><p>Restore a prior backup. The import itself is added to history.</p><button class="btn" id="import-settings">Choose file</button></section><section class="panel project-card"><div class="eyebrow">Reset</div><h3>Seed workspace</h3><p>Restore the demonstration dataset. Export first if you need your edits.</p><button class="btn" id="reset">Reset demo data</button></section></div><section class="panel" style="margin-top:16px"><div class="panel-body"><strong>Storage model</strong><p style="color:var(--muted);font-size:13px;line-height:1.7">Static GitHub Pages app + browser localStorage. No server account or database is required. Data is device/browser specific, so export backups regularly and commit important snapshots separately if desired.</p></div></section>`}

function strategicScore(fid){ const f=faculty(fid); const base=bestMatch(fid)?.score||f?.discoveryScore||0; const text=((f?.interests||[]).join(" ")+" "+(f?.why||"")).toLowerCase(); const multi=/(multimodal|vision-language|video|audio-visual|computer vision)/.test(text); const robot=/(robot|embodied|spatial|3d|human-object|navigation|manipulation)/.test(text); const onlyLanguage=!multi&&!robot&&/(nlp|language|llm|social)/.test(text); return Math.max(0,Math.min(99,base+(multi?5:0)+(robot?7:0)+(multi&&robot?5:0)-(onlyLanguage?12:0))); }
function gpaRisk(p){ return p.tier==="Dream"?"Very high":p.tier==="Reach"?"High":p.tier==="Target"?"Moderate-high":"Moderate"; }
function schoolScore(p){ const fs=state.faculty.filter(f=>f.programId===p.id&&(f.position!=="Faculty candidate"||f.reviewStatus==="confirmed")); const fit=fs.length?Math.max(...fs.map(f=>strategicScore(f.id))):45; const depth=Math.min(8,fs.filter(f=>strategicScore(f.id)>=80).length*3); const summer=(state.summerResearch||[]).some(x=>x.school===p.school)?4:0; const penalty=p.tier==="Dream"?12:p.tier==="Reach"?8:p.tier==="Target"?4:2; return Math.max(0,Math.min(99,Math.round(p.priority*.5+fit*.5+depth+summer-penalty))); }
function bestMatch(fid){return state.matches.filter(m=>m.facultyId===fid).sort((a,b)=>b.score-a.score)[0]}
function bestScore(fid){return strategicScore(fid)}
function hay(x){return JSON.stringify(x).toLowerCase()}
function toast(msg){let t=document.createElement("div");t.className="toast";t.textContent=msg;document.body.append(t);setTimeout(()=>t.remove(),2400)}
function modal(title,body,onSave){let w=document.createElement("div");w.className="modal-wrap";w.innerHTML=`<form class="modal"><div class="modal-head"><h2>${title}</h2><button type="button" class="icon-btn close">×</button></div><div class="modal-body">${body}</div><div class="modal-foot"><button type="button" class="btn close">Cancel</button><button class="btn primary">Save changes</button></div></form>`;document.body.append(w);w.querySelectorAll(".close").forEach(b=>b.onclick=()=>w.remove());w.onclick=e=>{if(e.target===w)w.remove()};w.querySelector("form").onsubmit=e=>{e.preventDefault();onSave(new FormData(e.target));w.remove();shell()}}
const field=(label,name,value="",type="text",full=false)=>`<div class="field ${full?"full":""}"><label>${label}</label>${type==="textarea"?`<textarea name="${name}">${esc(value)}</textarea>`:`<input name="${name}" type="${type}" value="${esc(value)}" required>`}</div>`;
function openForm(type,id){
 if(type==="program"){let x=state.programs.find(p=>p.id===id)||{};modal(id?"Edit program":"Add program",`<div class="form-grid">${field("School","school",x.school)}${field("Department","department",x.department)}${field("Program","program",x.program)}${field("City","city",x.city)}${field("State","state",x.state)}${field("Tier","tier",x.tier||"Target")}${field("Deadline","deadline",x.deadline||"2027-12-15","date")}${field("Priority 0–100","priority",x.priority||75,"number")}${field("Application fee","fee",x.fee||0,"number")}${field("GRE status","gre",x.gre||"Unknown")}${field("TOEFL minimum","toefl",x.toefl||"Unknown")}${field("Funding","funding",x.funding||"Unknown")}${field("Admission model","model",x.model||"Unknown",false,true)}</div>`,fd=>{let data=Object.fromEntries(fd);data.priority=+data.priority;data.fee=+data.fee;data.facultyCount=x.facultyCount||0;data.id=x.id||uid("pr");data.status=x.status||"Considering";id?Object.assign(x,data):state.programs.push(data);persist(id?"Program updated":"Program added",data.school,data.program)})}
 if(type==="faculty"){let x=state.faculty.find(f=>f.id===id)||{};modal(id?"Edit faculty":"Add faculty",`<div class="form-grid">${field("Name","name",x.name)}<div class="field"><label>Program</label><select name="programId">${state.programs.map(p=>`<option value="${p.id}" ${p.id===x.programId?"selected":""}>${esc(p.school)}</option>`).join("")}</select></div>${field("Position","position",x.position||"Professor")}${field("Website","website",x.website||"","url")}${field("Research interests (comma-separated)","interests",(x.interests||[]).join(", "),"textarea",true)}${field("Why consider","why",x.why||"","textarea",true)}${field("Concerns","concerns",x.concerns||"","textarea",true)}</div>`,fd=>{let data=Object.fromEntries(fd);data.interests=data.interests.split(",").map(s=>s.trim()).filter(Boolean);Object.assign(data,{id:x.id||uid("f"),recruiting:x.recruiting||"unknown",consideration:x.consideration||"not_reviewed",contact:x.contact||"not_planned",completion:x.completion||10,tsinghua:x.tsinghua||0,lastChecked:new Date().toISOString().slice(0,10),email:x.email||""});id?Object.assign(x,data):state.faculty.push(data);persist(id?"Faculty updated":"Faculty added",data.name,"Profile saved")})}
 if(type==="project"){let x=state.projects.find(p=>p.id===id)||{};modal(id?"Edit project":"Add project",`<div class="form-grid">${field("Project name","name",x.name)}${field("Short name","short",x.short)}${field("Research area","area",x.area)}${field("Status","status",x.status||"idea")}${field("Research problem","problem",x.problem||"","textarea",true)}${field("Method","method",x.method||"","textarea",true)}${field("My contribution","contribution",x.contribution||"","textarea",true)}${field("Keywords (comma-separated)","keywords",(x.keywords||[]).join(", "),"textarea",true)}</div>`,fd=>{let data=Object.fromEntries(fd);data.keywords=data.keywords.split(",").map(s=>s.trim()).filter(Boolean);data.id=x.id||uid("p");data.updated=new Date().toISOString().slice(0,10);id?Object.assign(x,data):state.projects.push(data);persist(id?"Project updated":"Project added",data.name,"Research profile changed")})}
 if(type==="task")modal("Add task",`<div class="form-grid">${field("Task","title")}${field("Due date","due",new Date().toISOString().slice(0,10),"date")}${field("Type","type","Research")}</div>`,fd=>{let x=Object.fromEntries(fd);x.id=uid("t");x.done=false;state.tasks.push(x);persist("Task added",x.title,fmt(x.due))});
 if(type==="application")modal("Add application",`<div class="form-grid"><div class="field full"><label>Program</label><select name="programId">${state.programs.map(p=>`<option value="${p.id}">${esc(p.school)} · ${esc(p.program)}</option>`).join("")}</select></div>${field("Deadline","deadline","2027-12-15","date")}${field("Notes","notes","","textarea",true)}</div>`,fd=>{let x=Object.fromEntries(fd);x.id=uid("a");x.status="Considering";x.progress=0;x.tasks=[];state.applications.push(x);persist("Application added",program(x.programId)?.school,"Tracker created")});
 if(type==="source")modal("Add evidence source",`<div class="form-grid">${field("Entity / claim","entity")}${field("Source name","name")}${field("URL","url","","url")}${field("Source type","type","official_department")}${field("Last checked","lastChecked",new Date().toISOString().slice(0,10),"date")}${field("Confidence","confidence","medium")}${field("Verification status","status","unverified")}${field("Evidence note","claim","","textarea",true)}</div>`,fd=>{let x=Object.fromEntries(fd);x.id=uid("s");state.sources.push(x);persist("Source added",x.entity,x.name)});
}
function showFaculty(id){let f=faculty(id),p=program(f.programId),m=bestMatch(id);modal(f.name,`<div class="detail-grid"><div class="detail-block"><h4>Research overview</h4><p>${f.interests.map(esc).join(" · ")}</p></div><div class="detail-block"><h4>Decision</h4><p>${esc(f.consideration.replaceAll("_"," "))} · ${f.completion}% researched</p></div><div class="detail-block full"><h4>Best project match · ${esc(project(m.projectId)?.name)} · ${m.score}</h4><p>${esc(m.explanation)}</p></div><div class="detail-block full"><h4>Possible pitch</h4><p>${esc(m.pitch)}</p></div><div class="detail-block"><h4>Why consider</h4><p>${esc(f.why)}</p></div><div class="detail-block"><h4>Concerns</h4><p>${esc(f.concerns)}</p></div><div class="detail-block"><h4>Lab & Tsinghua network</h4><p>${f.tsinghua} connection(s) tracked · detailed member schema ready</p></div><div class="detail-block"><h4>Evidence</h4><p>${esc(f.recruiting.replaceAll("_"," "))} · checked ${fmt(f.lastChecked)}</p></div></div>`,()=>{});document.querySelector(".modal-foot").remove()}
function showMatch(key){let [fid,pid]=key.split(":"),m=state.matches.find(x=>x.facultyId===fid&&x.projectId===pid);if(!m)return;modal(`${faculty(fid).name} × ${project(pid).short}`,`<div class="detail-grid">${["topic","method","data","multimodal","llm","recent","collaboration"].map(k=>`<div class="detail-block"><h4>${k[0].toUpperCase()+k.slice(1)} fit</h4><div class="score">${m[k]}</div><div class="progress"><i style="width:${m[k]}%"></i></div></div>`).join("")}<div class="detail-block full"><h4>Why this match</h4><p>${esc(m.explanation)}</p></div><div class="detail-block full"><h4>Possible research pitch</h4><p>${esc(m.pitch)}</p></div></div>`,()=>{});document.querySelector(".modal-foot").remove()}
function download(){let blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`phd-application-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);state.history.unshift({id:uid("h"),at:new Date().toISOString(),action:"Backup exported",entity:"Workspace",detail:a.download});localStorage.setItem(STORAGE_KEY,JSON.stringify(state));toast("完整备份已下载")}
function bind(){
 document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{currentView=b.dataset.view;query="";shell()});
 document.getElementById("global-search")?.addEventListener("input",e=>{query=e.target.value;document.getElementById("content").innerHTML=renderView();bindContent()});
 document.getElementById("theme").onclick=()=>{let t=document.documentElement.dataset.theme==="dark"?"light":"dark";localStorage.setItem("theme",t);document.documentElement.dataset.theme=t};
 document.getElementById("menu").onclick=()=>document.getElementById("sidebar").classList.toggle("open");document.getElementById("export").onclick=download;bindContent();
}
function bindContent(){
 window.extendedBind?.();
 document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>openForm(b.dataset.add));document.querySelectorAll("[data-edit-program]").forEach(b=>b.onclick=()=>openForm("program",b.dataset.editProgram));document.querySelectorAll("[data-edit-project]").forEach(b=>b.onclick=()=>openForm("project",b.dataset.editProject));document.querySelectorAll("[data-faculty]").forEach(b=>b.onclick=e=>{e.preventDefault();showFaculty(b.dataset.faculty)});document.querySelectorAll("[data-match]").forEach(b=>b.onclick=()=>showMatch(b.dataset.match));
 document.querySelectorAll("[data-task]").forEach(b=>b.onchange=()=>{let t=state.tasks.find(x=>x.id===b.dataset.task);t.done=b.checked;persist("Task updated",t.title,b.checked?"Completed":"Reopened");shell()});
 document.querySelectorAll(".quick-status").forEach(s=>s.onchange=()=>{let f=faculty(s.dataset.id);f.consideration=s.value;persist("Consideration changed",f.name,s.value)});document.querySelectorAll(".app-status").forEach(s=>s.onchange=()=>{let a=state.applications.find(x=>x.id===s.dataset.id);a.status=s.value;persist("Application status changed",program(a.programId)?.school,s.value)});document.querySelectorAll(".contact-status").forEach(s=>s.onchange=()=>{let f=faculty(s.dataset.id);f.contact=s.value;persist("Contact status changed",f.name,s.value)});
 let tf=document.getElementById("tier-filter");if(tf)tf.onchange=()=>document.querySelectorAll("[data-tier]").forEach(r=>r.style.display=!tf.value||r.dataset.tier===tf.value?"":"none");let ff=document.getElementById("faculty-filter");if(ff)ff.onchange=()=>document.querySelectorAll("[data-consideration]").forEach(r=>r.style.display=!ff.value||r.dataset.consideration===ff.value?"":"none");
 document.getElementById("export-settings")?.addEventListener("click",download);document.getElementById("import-settings")?.addEventListener("click",()=>document.getElementById("import-file").click());document.getElementById("reset")?.addEventListener("click",()=>{if(confirm("Reset all local data to the demo dataset?")){state=clone(window.SEED_DATA);persist("Workspace reset","Workspace","Demo data restored");shell()}});
}
document.getElementById("import-file").addEventListener("change",e=>{let file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.meta||!x.programs||!x.faculty)throw Error();state=x;persist("Backup imported","Workspace",file.name);shell()}catch{alert("Invalid backup file")}};r.readAsText(file)});
shell();
