(function(){
  const E=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const entities=["programs","faculty","applications","sources","deadlines","contactRecords","papers","labMembers","communityClaims"];
  const csvCell=v=>`"${String(v??"").replaceAll('"','""')}"`;
  function download(name,text,type="text/csv") {const blob=new Blob([text],{type}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href);}
  function exportCsv(key){const rows=state[key]||[];if(!rows.length){alert("No records to export");return}const headers=[...new Set(rows.flatMap(Object.keys))].filter(x=>!headersUnsafe(x));const csv=[headers.map(csvCell).join(","),...rows.map(row=>headers.map(h=>csvCell(typeof row[h]==="object"?JSON.stringify(row[h]):row[h])).join(","))].join("\n");download(`${key}-${new Date().toISOString().slice(0,10)}.csv`,csv);persist("CSV exported",key,`${rows.length} records`);}
  function headersUnsafe(x){return x==="history"}
  function parseCsv(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"'){quoted=!quoted}else if(c===","&&!quoted){row.push(cell);cell=""}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&n==="\n")i++;row.push(cell);if(row.some(x=>x!==""))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(x=>x!==""))rows.push(row);return rows;}
  function importCsv(key,file){const reader=new FileReader();reader.onload=()=>{try{const rows=parseCsv(reader.result);const headers=rows.shift();let count=0;for(const cells of rows){const record={};headers.forEach((h,i)=>{let v=cells[i]??"";if((v.startsWith("{")&&v.endsWith("}"))||(v.startsWith("[")&&v.endsWith("]")))try{v=JSON.parse(v)}catch{}record[h]=v});record.id=record.id||key.slice(0,3)+Date.now().toString(36)+count;(state[key]||(state[key]=[])).push(record);count++}persist("CSV imported",key,`${count} records from ${file.name}`);shell()}catch(e){alert("CSV import failed: "+e.message)}};reader.readAsText(file);}
  function profileForm(){const p=state.profile,wrap=document.createElement("div");wrap.className="modal-wrap";wrap.innerHTML=`<form class="modal"><div class="modal-head"><h2>Edit Candidate Profile</h2><button type="button" class="icon-btn close-profile">×</button></div><div class="modal-body"><div class="form-grid"><div class="field"><label>Name</label><input name="name" value="${E(p.name)}"></div><div class="field"><label>GPA</label><input name="gpa" type="number" step="0.01" value="${E(p.gpa)}"></div><div class="field"><label>Institution</label><input name="institution" value="${E(p.institution)}"></div><div class="field"><label>Department</label><input name="department" value="${E(p.department)}"></div><div class="field"><label>Degree</label><input name="degree" value="${E(p.degree)}"></div><div class="field"><label>Application cycle</label><input name="cycle" value="${E(p.cycle)}"></div><div class="field full"><label>Target</label><input name="target" value="${E(p.target)}"></div><div class="field full"><label>Research focus (comma-separated)</label><textarea name="focus">${E((p.focus||[]).join(", "))}</textarea></div><div class="field full"><label>Research statement</label><textarea name="statement">${E(p.statement)}</textarea></div></div></div><div class="modal-foot"><button type="button" class="btn close-profile">Cancel</button><button class="btn primary">Save profile</button></div></form>`;document.body.append(wrap);wrap.querySelectorAll(".close-profile").forEach(x=>x.onclick=()=>wrap.remove());wrap.querySelector("form").onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);for(const key of ["name","institution","department","degree","cycle","target","statement"])p[key]=fd.get(key);p.gpa=Number(fd.get("gpa"));p.focus=fd.get("focus").split(",").map(x=>x.trim()).filter(Boolean);persist("Candidate profile updated","CandidateProfile",`GPA ${p.gpa}; ${p.focus.join(", ")}`);wrap.remove();shell()};}
  function exportCv(kind){const include=kind==="academic"?"includeAcademic":"includeApplication",rows=state.cvItems.filter(x=>x[include]);download(`${kind}-cv-data.json`,JSON.stringify({profile:state.profile,items:rows},null,2),"application/json");persist("CV data exported",kind,`${rows.length} items`);}
  window.extendedViews.settings=()=>`${head("Local-first data control","Settings & Data","Portable JSON/CSV, structured CV exports and browser-local persistence.")}<div class="grid three-col"><section class="panel project-card"><div class="eyebrow">Full backup</div><h3>JSON snapshot</h3><p>Includes every entity and audit event.</p><button class="btn primary" id="export-settings">Export JSON</button><button class="btn" id="import-settings">Import JSON</button></section><section class="panel project-card"><div class="eyebrow">Entity exchange</div><h3>CSV import / export</h3><p>Programs, faculty, applications, sources, deadlines and intelligence records.</p><select id="csv-entity" style="width:100%;padding:9px;margin-bottom:8px">${entities.map(x=>`<option>${x}</option>`).join("")}</select><button class="btn" id="csv-export">Export CSV</button><button class="btn" id="csv-import">Import CSV</button><input type="file" id="csv-file" accept=".csv,text/csv" hidden></section><section class="panel project-card"><div class="eyebrow">CV outputs</div><h3>Structured CV data</h3><p>Separate Academic and Application variants.</p><button class="btn" data-cv-export="academic">Academic CV</button><button class="btn" data-cv-export="application">Application CV</button></section></div><section class="panel" style="margin-top:16px"><div class="panel-body"><strong>Storage and history</strong><p style="color:var(--muted);font-size:13px">Changes remain in this browser and create audit events. Use JSON for complete restoration and CSV for entity-level exchange. Export backups before clearing site data or switching devices.</p></div></section>`;
  const previous=window.extendedBind;window.extendedBind=function(){previous?.();document.querySelector("[data-edit-profile]")?.addEventListener("click",profileForm);document.getElementById("export-settings")?.addEventListener("click",download);document.getElementById("import-settings")?.addEventListener("click",()=>document.getElementById("import-file").click());const select=document.getElementById("csv-entity"),file=document.getElementById("csv-file");document.getElementById("csv-export")?.addEventListener("click",()=>exportCsv(select.value));document.getElementById("csv-import")?.addEventListener("click",()=>file.click());file?.addEventListener("change",()=>file.files[0]&&importCsv(select.value,file.files[0]));document.querySelectorAll("[data-cv-export]").forEach(x=>x.onclick=()=>exportCv(x.dataset.cvExport));};
})();
