(function(){
  const E=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const badge=v=>`<span class="status ${statusClass(v)}">${E(String(v||"—").replaceAll("_"," "))}</span>`;
  const qualitative=["researchFit","department","funding","city","labCulture","placement","internship","industry","academicPlacement","advisorStability"];
  const defaultWeights={researchFit:25,department:8,funding:12,city:5,labCulture:15,placement:10,internship:5,industry:5,academicPlacement:8,advisorStability:7};
  function offerWeights(x){try{return {...defaultWeights,...JSON.parse(x.weights||"{}")}}catch{return defaultWeights}}
  function offerScore(x){const w=offerWeights(x),total=qualitative.reduce((n,k)=>n+Number(w[k]||0),0)||100;return Math.round(qualitative.reduce((n,k)=>n+Number(x[k]||0)*Number(w[k]||0),0)/total*10)}
  function testReadiness(){const toefl=state.tests.filter(x=>x.type==="TOEFL"&&x.total!=="").sort((a,b)=>String(b.testDate).localeCompare(String(a.testDate)))[0],score=Number(toefl?.total||0);return state.programs.map(p=>{const min=Number(String(p.toefl||"").match(/\d+/)?.[0]||0),status=!min?"needs_verification":!score?"score_missing":score>=min?"satisfied":"below_minimum";return {p,min,status,score}})}
  const oldDashboard=window.extendedViews.dashboard;window.extendedViews.dashboard=()=>{const base=oldDashboard?oldDashboard():dashboard(),today=new Date(),reminders=state.recommendations.filter(x=>!x.submitted&&x.deadline).map(x=>({...x,days:Math.ceil((new Date(x.deadline+"T00:00:00")-today)/86400000)})).filter(x=>[0,1,2,3,4,5,6,7].includes(x.days)).sort((a,b)=>a.days-b.days);return `${base}<section class="panel" style="margin-top:16px"><div class="panel-head"><h2>Recommendation reminders</h2><span>7 / 3 / deadline-day window</span></div><div class="panel-body">${reminders.length?reminders.map(x=>`<div class="task"><div class="task-info"><div class="task-title">${E(state.recommenders.find(r=>r.id===x.recommenderId)?.name||"Recommender")} · ${E(program(state.applications.find(a=>a.id===x.applicationId)?.programId)?.school)}</div><div class="task-meta">Due ${fmt(x.deadline)} · materials: ${E(x.materialsSent||"not recorded")}</div></div>${badge(x.days===0?"deadline day":x.days<=3?"under 3 days":"under 7 days")}</div>`).join(""):`<div class="empty">No recommendation reminders in the next 7 days.</div>`}</div></section>`};
  window.extendedViews.tests=()=>{const rows=testReadiness();return `${head("Standardized tests","Test Tracker & Requirement Check","Section scores, targets and program-by-program readiness; requirements remain source-dependent.",`<button class="btn primary" data-ext-add="tests">+ Test record</button>`)}<div class="grid two-col"><section class="panel"><div class="panel-head"><h2>Scores</h2><span>${state.tests.length}</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Test</th><th>Date</th><th>Total</th><th>Sections</th><th>Target</th><th></th></tr></thead><tbody>${state.tests.map(x=>`<tr><td>${E(x.type)}</td><td>${fmt(x.testDate)}</td><td><span class="score">${E(x.total||"—")}</span></td><td>R ${E(x.reading||"—")} · L ${E(x.listening||"—")} · S ${E(x.speaking||"—")} · W ${E(x.writing||"—")}</td><td>${E(x.targetScore)}</td><td><button class="btn subtle" data-ext-edit="tests:${x.id}">Edit</button></td></tr>`).join("")}</tbody></table></div></section><section class="panel"><div class="panel-head"><h2>Program readiness</h2><span>TOEFL</span></div><div class="panel-body" style="max-height:520px;overflow:auto">${rows.map(x=>`<div class="queue-item"><div class="queue-top"><strong>${E(x.p.school)}</strong>${badge(x.status)}</div><p>Current ${x.score||"—"} · listed minimum ${x.min||"verify"} · source must be rechecked for 2028</p></div>`).join("")}</div></section></div>`};
  window.extendedViews.offers=()=>`${head("Decision matrix","Offer Comparison","Raw dimensions, custom weights and transparent calculated score.",`<button class="btn primary" data-ext-add="offers">+ Offer</button>`)}<div class="panel" style="margin-bottom:16px"><div class="panel-body"><div class="keywords">${Object.entries(defaultWeights).map(([k,v])=>`<span class="tag">${E(k)} ${v}%</span>`).join("")}</div><p class="subtext">Each offer can override these defaults with JSON weights. Raw values remain stored.</p></div></div><div class="cards">${state.offers.length?state.offers.sort((a,b)=>offerScore(b)-offerScore(a)).map(x=>`<article class="panel project-card"><div style="display:flex;justify-content:space-between"><span class="status green">Offer</span><span class="score">${offerScore(x)}</span></div><h3>${E(program(x.programId)?.school)}</h3><p>${E(x.advisor||"Advisor TBD")}</p><div class="detail-grid"><div><div class="subtext">Research fit</div><strong>${E(x.researchFit)}/10</strong></div><div><div class="subtext">Lab culture</div><strong>${E(x.labCulture)}/10</strong></div><div><div class="subtext">Stipend</div><strong>$${Number(x.stipend||0).toLocaleString()}</strong></div><div><div class="subtext">Cost of living</div><strong>$${Number(x.costOfLiving||0).toLocaleString()}</strong></div></div><p>${E(x.notes)}</p><button class="btn subtle" data-ext-edit="offers:${x.id}">Edit raw fields</button></article>`).join(""):`<section class="panel"><div class="empty">No offers yet. The matrix becomes active after an offer is recorded.</div></section>`}</div>`;
})();
