(function(){
  if(!window.SEED_DATA.verificationRecords) window.SEED_DATA.verificationRecords=[
    {id:"vr1",entityType:"Program",entityId:"pr1",field:"deadline",value:"2027-12-05",sourceId:"s1",status:"outdated",checkedAt:"2026-08-10",notes:"Placeholder; recheck for the 2028 cycle."},
    {id:"vr2",entityType:"Program",entityId:"pr3",field:"funding",value:"Fully funded",sourceId:"s3",status:"outdated",checkedAt:"2026-08-11",notes:"Funding package must be confirmed for the application cycle."}
  ];
  const E=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const badge=v=>`<span class="status ${statusClass(v)}">${E(String(v||"—").replaceAll("_"," "))}</span>`;
  const priority=s=>({official_department:100,official_graduate_school:100,faculty_website:95,lab_website:92,official_candidate:85,professional:60,secondary_source:55,community:30}[s?.type]||40);
  const source=id=>(state.sources||[]).find(x=>x.id===id);
  const entityName=r=>r.entityType==="Program"?program(r.entityId)?.school:r.entityType==="Faculty"?faculty(r.entityId)?.name:r.entityId;
  function conflicts(record){return state.verificationRecords.filter(x=>x.entityType===record.entityType&&x.entityId===record.entityId&&x.field===record.field&&x.id!==record.id&&x.value!==record.value&&x.status!=="outdated")}
  function form(recordId){const list=state.verificationRecords,old=list.find(x=>x.id===recordId)||{},wrap=document.createElement("div");wrap.className="modal-wrap";wrap.innerHTML=`<form class="modal"><div class="modal-head"><h2>${recordId?"Edit":"Add"} verification record</h2><button type="button" class="icon-btn ev-close">×</button></div><div class="modal-body"><div class="form-grid"><div class="field"><label>Entity type</label><select name="entityType">${["Program","Faculty","Application","SummerResearch"].map(x=>`<option ${x===old.entityType?"selected":""}>${x}</option>`).join("")}</select></div><div class="field"><label>Entity ID</label><input name="entityId" value="${E(old.entityId)}" required></div><div class="field"><label>Field</label><select name="field">${["deadline","GRE requirement","TOEFL requirement","IELTS requirement","funding","recruiting","admission model","application fee","international eligibility","contact information"].map(x=>`<option ${x===old.field?"selected":""}>${x}</option>`).join("")}</select></div><div class="field"><label>Observed value</label><input name="value" value="${E(old.value)}" required></div><div class="field"><label>Source</label><select name="sourceId">${state.sources.map(x=>`<option value="${x.id}" ${x.id===old.sourceId?"selected":""}>${E(x.entity)} · ${E(x.name)}</option>`).join("")}</select></div><div class="field"><label>Status</label><select name="status">${["official_confirmed","secondary_source","unverified","outdated","partially_corroborated","corroborated","contradicted"].map(x=>`<option ${x===old.status?"selected":""}>${x}</option>`).join("")}</select></div><div class="field"><label>Checked at</label><input type="date" name="checkedAt" value="${E(old.checkedAt||new Date().toISOString().slice(0,10))}"></div><div class="field full"><label>Notes</label><textarea name="notes">${E(old.notes)}</textarea></div></div></div><div class="modal-foot"><button type="button" class="btn ev-close">Cancel</button><button class="btn primary">Save evidence</button></div></form>`;document.body.append(wrap);wrap.querySelectorAll(".ev-close").forEach(x=>x.onclick=()=>wrap.remove());wrap.querySelector("form").onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.id=old.id||"vr"+Date.now().toString(36);old.id?Object.assign(old,data):list.unshift(data);persist(`Verification ${old.id?"updated":"added"}`,`${data.entityType}.${data.field}`,data.value);wrap.remove();shell()};}
  function verificationPanel(){const needs=state.verificationRecords.filter(x=>["outdated","unverified","contradicted"].includes(x.status)).slice(0,8);return `<section class="panel" style="margin-top:16px"><div class="panel-head"><h2>Information needing verification</h2><span>${needs.length} highest-priority items</span></div><div class="panel-body">${needs.length?needs.map(x=>`<div class="queue-item"><div class="queue-top"><strong>${E(entityName(x))} · ${E(x.field)}</strong>${badge(x.status)}</div><p>${E(x.value)} · checked ${fmt(x.checkedAt)} · source priority ${priority(source(x.sourceId))}</p></div>`).join(""):`<div class="empty">No verification items.</div>`}</div></section>`}
  const oldDashboard=window.extendedViews.dashboard;window.extendedViews.dashboard=()=>`${oldDashboard?oldDashboard():dashboard()}${verificationPanel()}`;
  window.extendedViews.sources=()=>{const records=[...state.verificationRecords].sort((a,b)=>priority(source(b.sourceId))-priority(source(a.sourceId)));return `${head("Traceable evidence","Sources & Field Verification","Official evidence takes precedence; conflicts and stale records remain visible.",`<button class="btn" data-add="source">+ Source</button><button class="btn primary" id="add-verification">+ Verification</button>`)}<div class="grid stats">${stat("Sources",state.sources.length,"All evidence objects")}${stat("Field records",records.length,"Observed values")}${stat("Official confirmed",records.filter(x=>x.status==="official_confirmed").length,"Highest confidence")}${stat("Need recheck",records.filter(x=>["outdated","unverified"].includes(x.status)).length,"Action queue")}${stat("Conflicts",records.filter(x=>conflicts(x).length).length,"Multiple active values")}</div><section class="panel"><div class="panel-head"><h2>Field-level verification</h2><span>Sorted by source authority</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Entity / field</th><th>Observed value</th><th>Source</th><th>Authority</th><th>Checked</th><th>Status</th><th>Conflict</th><th></th></tr></thead><tbody>${records.map(x=>{const s=source(x.sourceId),c=conflicts(x);return `<tr><td><div class="school-name">${E(entityName(x))}</div><div class="subtext">${E(x.entityType)} · ${E(x.field)}</div></td><td>${E(x.value)}</td><td>${s?`<a href="${E(s.url)}" target="_blank">${E(s.name)} ↗</a>`:"Missing source"}</td><td>${priority(s)}</td><td>${fmt(x.checkedAt)}</td><td>${badge(x.status)}</td><td>${c.length?badge("contradicted"):`<span class="status green">none</span>`}</td><td><button class="btn subtle" data-verification-edit="${x.id}">Edit</button></td></tr>`}).join("")}</tbody></table></div></section><section class="panel" style="margin-top:16px"><div class="panel-head"><h2>Source registry</h2><span>${state.sources.length} records</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Entity</th><th>Source</th><th>Type</th><th>Last checked</th><th>Confidence</th><th>Status</th></tr></thead><tbody>${state.sources.slice(0,300).map(s=>`<tr><td>${E(s.entity)}</td><td><a href="${E(s.url)}" target="_blank">${E(s.name)} ↗</a></td><td>${E(s.type)}</td><td>${fmt(s.lastChecked)}</td><td>${badge(s.confidence)}</td><td>${badge(s.status)}</td></tr>`).join("")}</tbody></table></div></section>`};
  const previous=window.extendedBind;window.extendedBind=function(){previous?.();document.getElementById("add-verification")?.addEventListener("click",()=>form());document.querySelectorAll("[data-verification-edit]").forEach(x=>x.onclick=()=>form(x.dataset.verificationEdit));};
})();
