(function () {
  const E = value => String(value ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const id = prefix => prefix + Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
  const label = (items, value, field="name") => (items || []).find(x => x.id === value)?.[field] || "—";
  const options = {
    faculty: () => state.faculty.map(x => [x.id, `${x.name} · ${program(x.programId)?.school || ""}`]),
    projects: () => state.projects.map(x => [x.id, x.name]),
    programs: () => state.programs.map(x => [x.id, `${x.school} · ${x.program}`]),
    applications: () => state.applications.map(x => [x.id, program(x.programId)?.school || x.id]),
    recommenders: () => state.recommenders.map(x => [x.id, x.name])
  };
  const schemas = {
    papers: {title:"Paper", prefix:"paper", fields:[
      ["title","Paper title"],["facultyId","Faculty","select",options.faculty],["authors","Authors"],["venue","Venue"],["year","Year","number"],["url","URL","url"],["topic","Research topic"],["projectId","Related project","select",options.projects],["importance","Importance","select",["must_read","high","medium","low"]],["readingStatus","Reading status","select",["unread","reading","read","summarized"]],["whyRelevant","Why relevant to me","textarea"],["potentialGap","Potential gap","textarea"],["notes","Notes","textarea"]]},
    publications: {title:"Publication",prefix:"pub",fields:[["title","Title"],["projectId","Project","select",options.projects],["venue","Venue"],["year","Year","number"],["status","Status","select",["working","draft","submitted","under_review","rebuttal","accepted","rejected","resubmitting"]],["authorOrder","Author order","number"],["coauthors","Coauthors"],["advisor","Advisor"],["submissionDeadline","Submission deadline","date"],["reviewDate","Review date","date"],["cameraReady","Camera ready","date"]]},
    sopDocuments: {title:"SOP document",prefix:"sop",fields:[["school","School / Master"],["facultyMentions","Faculty mentions"],["researchFit","Research fit","textarea"],["projectsUsed","Projects used"],["wordLimit","Word limit","number"],["version","Version"],["status","Status","select",["outline","drafting","review","ready","submitted"]],["opening","Opening","textarea"],["research1","Research experience 1","textarea"],["research2","Research experience 2","textarea"],["futureResearch","Future research","textarea"],["whyProgram","Why this program","textarea"],["facultyFit","Faculty fit","textarea"],["careerGoal","Career goal","textarea"]]},
    recommenders: {title:"Recommender",prefix:"rec",fields:[["name","Name"],["institution","Institution"],["relationship","Relationship"],["projectsWorked","Projects worked together"],["strengthEstimate","Strength estimate","select",["unknown","developing","strong","very_strong"]],["letterStatus","Letter status","select",["not_discussed","planning","agreed","requested","submitted"]],["notes","Notes","textarea"]]},
    recommendations: {title:"Recommendation request",prefix:"req",fields:[["recommenderId","Recommender","select",options.recommenders],["applicationId","Application","select",options.applications],["requested","Requested","checkbox"],["requestDate","Request date","date"],["deadline","Deadline","date"],["submitted","Submitted","checkbox"],["thankYouSent","Thank-you sent","checkbox"],["materialsSent","Materials sent (CV, SOP, summary...)"],["notes","Notes","textarea"]]},
    contactRecords: {title:"Faculty contact",prefix:"contact",fields:[["facultyId","Faculty","select",options.faculty],["status","Status","select",["not_planned","planning","drafted","sent","replied","follow_up","meeting","no_response"]],["subject","Subject"],["draft","Personalized email draft","textarea"],["facultyReference","Faculty research reference","textarea"],["relatedProject","My related project","select",options.projects],["paperCited","Paper cited"],["dateSent","Date sent","date"],["replyDate","Reply date","date"],["followUpDate","Follow-up date","date"],["responseType","Response type","select",["","positive","neutral","not_recruiting","apply_normally","meeting_requested","negative"]],["responseSummary","Response summary","textarea"]]},
    tests: {title:"Test record",prefix:"test",fields:[["type","Test","select",["TOEFL","IELTS","GRE"]],["testDate","Test date","date"],["registrationDeadline","Registration deadline","date"],["reading","Reading"],["listening","Listening"],["speaking","Speaking"],["writing","Writing"],["verbal","Verbal"],["quantitative","Quantitative"],["total","Total"],["targetScore","Target score"],["notes","Notes","textarea"]]},
    cvItems: {title:"CV item",prefix:"cv",fields:[["section","Section","select",["Education","Research Experience","Publications","Projects","Awards","Teaching","Skills","Service"]],["title","Title"],["organization","Organization"],["startDate","Start date"],["endDate","End date"],["description","Description","textarea"],["includeAcademic","Academic CV","checkbox"],["includeApplication","Application CV","checkbox"]]},
    interviews: {title:"Interview",prefix:"int",fields:[["applicationId","Application","select",options.applications],["facultyId","Faculty","select",options.faculty],["date","Date","datetime-local"],["format","Format"],["duration","Duration (minutes)","number"],["facultyPapers","Faculty papers","textarea"],["projectPitch","My project pitch","textarea"],["whyPhd","Why PhD","textarea"],["whyLab","Why this lab","textarea"],["researchIdeas","Research ideas","textarea"],["questionsToAsk","Questions to ask","textarea"],["questionsAsked","Questions asked","textarea"],["myAnswers","My answers","textarea"],["facultyComments","Faculty comments","textarea"],["followUp","Follow-up","textarea"]]},
    offers: {title:"Offer",prefix:"offer",fields:[["programId","Program","select",options.programs],["advisor","Advisor"],["researchFit","Research fit 0–10","number"],["department","Department 0–10","number"],["funding","Funding 0–10","number"],["stipend","Stipend","number"],["costOfLiving","Cost of living","number"],["city","City 0–10","number"],["labCulture","Lab culture 0–10","number"],["placement","Placement 0–10","number"],["internship","Internship 0–10","number"],["industry","Industry connection 0–10","number"],["academicPlacement","Academic placement 0–10","number"],["advisorStability","Advisor stability 0–10","number"],["graduationTime","Expected years","number"],["weights","Custom weights (JSON)","textarea"],["notes","Notes","textarea"]]},
    costs: {title:"Cost item",prefix:"cost",fields:[["applicationId","Application","select",options.applications],["category","Category","select",["Application Fee","TOEFL Score Report","GRE Score Report","Transcript","Credential Evaluation","Travel","Visa","Other"]],["estimated","Estimated","number"],["actual","Actual","number"],["currency","Currency"],["notes","Notes","textarea"]]},
    labMembers: {title:"Lab member / alumnus",prefix:"member",fields:[["facultyId","Faculty","select",options.faculty],["name","Name"],["role","Role","select",["PhD Student","Master Student","Postdoc","Research Scientist","Visiting Student","Alumni"]],["undergraduateInstitution","Undergraduate institution"],["masterInstitution","Master institution"],["phdInstitution","PhD institution"],["previousInstitutions","Previous institutions"],["isTsinghuaAlumni","Tsinghua connection","select",["unknown","true","false"]],["tsinghuaDegree","Tsinghua degree"],["tsinghuaDepartment","Tsinghua department"],["tsinghuaGraduationYear","Graduation year"],["homepage","Homepage","url"],["scholar","Google Scholar","url"],["linkedin","LinkedIn","url"],["github","GitHub","url"],["publicEmail","Public email","email"],["contactSource","Contact source URL","url"],["contactCandidateScore","Contact candidate score","number"],["whyUseful","Why this person may be useful","textarea"]]},
    communityClaims: {title:"Community evidence claim",prefix:"claim",fields:[["facultyId","Faculty","select",options.faculty],["sourcePlatform","Platform","select",["Reddit","GradCafe","知乎","小红书","一亩三分地","Forum","Blog","Other"]],["sourceUrl","Source URL","url"],["sourceAuthor","Public author"],["postedDate","Posted date","date"],["collectedDate","Collected date","date"],["rawClaim","Raw claim","textarea"],["category","Category","select",["recruiting","funding","advisor_style","lab_culture","workload","meeting_frequency","student_autonomy","paper_expectation","graduation_time","internship_policy","industry_collaboration","placement","advisor_response_style","application_process","interview","offer","student_background","alumni_destination","group_stability"]],["reliability","Reliability","select",["low","medium","high"]],["verification","Verification","select",["unverified","partially_corroborated","corroborated","contradicted","outdated"]],["notes","Notes","textarea"]]},
    facultyTimeline: {title:"Faculty timeline event",prefix:"event",fields:[["facultyId","Faculty","select",options.faculty],["date","Date","date"],["type","Event type"],["detail","Detail","textarea"],["sourceUrl","Source URL","url"]]},
    notes: {title:"Note",prefix:"note",fields:[["entityType","Entity type","select",["School","Program","Faculty","Paper","Project","SOP","Interview","Application","General"]],["entityId","Entity ID"],["body","Note","textarea"],["tags","Tags (comma-separated)"],["createdAt","Created at","datetime-local"]]}
  };

  function inputFor(field, item) {
    const [name, title, type="text", source] = field;
    const value = item?.[name] ?? "";
    if (type === "textarea") return `<div class="field full"><label>${E(title)}</label><textarea name="${name}">${E(value)}</textarea></div>`;
    if (type === "checkbox") return `<div class="field"><label><input name="${name}" type="checkbox" ${value ? "checked" : ""}> ${E(title)}</label></div>`;
    if (type === "select") {
      const raw = typeof source === "function" ? source() : source || [];
      const list = raw.map(x => Array.isArray(x) ? x : [x, x]);
      return `<div class="field"><label>${E(title)}</label><select name="${name}"><option value="">—</option>${list.map(([v,l]) => `<option value="${E(v)}" ${String(v)===String(value)?"selected":""}>${E(l)}</option>`).join("")}</select></div>`;
    }
    return `<div class="field"><label>${E(title)}</label><input name="${name}" type="${type}" value="${E(value)}"></div>`;
  }
  function openForm(key, recordId) {
    const schema = schemas[key]; const list = state[key] || []; const current = list.find(x => x.id === recordId) || {};
    const wrap = document.createElement("div"); wrap.className = "modal-wrap";
    wrap.innerHTML = `<form class="modal"><div class="modal-head"><h2>${recordId?"Edit":"Add"} ${E(schema.title)}</h2><button type="button" class="icon-btn ext-close">×</button></div><div class="modal-body"><div class="form-grid">${schema.fields.map(f=>inputFor(f,current)).join("")}</div></div><div class="modal-foot">${recordId?`<button type="button" class="btn ext-delete">Delete</button>`:""}<button type="button" class="btn ext-close">Cancel</button><button class="btn primary">Save</button></div></form>`;
    document.body.append(wrap);
    wrap.querySelectorAll(".ext-close").forEach(x => x.onclick=()=>wrap.remove());
    wrap.onclick = ev => { if(ev.target===wrap) wrap.remove(); };
    wrap.querySelector(".ext-delete")?.addEventListener("click",()=>{ if(confirm(`Delete this ${schema.title}?`)){ state[key]=list.filter(x=>x.id!==recordId); persist(`${schema.title} deleted`,schema.title,current.title||current.name||recordId); wrap.remove(); shell(); }});
    wrap.querySelector("form").onsubmit = ev => {
      ev.preventDefault(); const fd=new FormData(ev.target); const data={...current};
      for(const [name,,type] of schema.fields) data[name]=type==="checkbox"?fd.has(name):fd.get(name)??"";
      data.id=current.id||id(schema.prefix); data.updatedAt=new Date().toISOString();
      if(current.id) Object.assign(current,data); else list.unshift(data);
      state[key]=list; persist(`${schema.title} ${current.id?"updated":"added"}`,schema.title,data.title||data.name||data.school||data.id); wrap.remove(); shell();
    };
  }
  function page(key, kicker, title, subtitle, columns) {
    const rows=state[key]||[]; const schema=schemas[key];
    return `${head(kicker,title,subtitle,`<button class="btn primary" data-ext-add="${key}">+ Add ${E(schema.title)}</button>`)}<section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr>${columns.map(x=>`<th>${E(x[0])}</th>`).join("")}<th></th></tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${columns.map(([,fn])=>`<td>${fn(row)}</td>`).join("")}<td><button class="btn subtle" data-ext-edit="${key}:${row.id}">Edit</button></td></tr>`).join(""):`<tr><td colspan="${columns.length+1}"><div class="empty">No records yet. Add the first ${E(schema.title.toLowerCase())}.</div></td></tr>`}</tbody></table></div></section>`;
  }
  const badge = v => `<span class="status ${statusClass(v)}">${E(String(v||"—").replaceAll("_"," "))}</span>`;
  const money = n => Number(n||0).toLocaleString("en-US",{maximumFractionDigits:0});
  const views = {
    papers: () => page("papers","Reading intelligence","Paper Tracking","Connect faculty papers to projects, relevance, gaps and reading status.",[["Paper",x=>`<div class="school-name">${E(x.title)}</div><div class="subtext">${E(x.authors)} · ${E(x.venue)} ${E(x.year)}</div>`],["Faculty",x=>E(label(state.faculty,x.facultyId))],["Project",x=>E(label(state.projects,x.projectId))],["Importance",x=>badge(x.importance)],["Reading",x=>badge(x.readingStatus)],["Why relevant / gap",x=>`${E(x.whyRelevant)}<div class="subtext">Gap: ${E(x.potentialGap)}</div>`]]),
    publications: () => page("publications","Research output","Publication Tracker","Track submission, review, rebuttal, acceptance and resubmission lifecycles.",[["Title",x=>`<div class="school-name">${E(x.title)}</div><div class="subtext">${E(x.venue)} · ${E(x.year)}</div>`],["Project",x=>E(label(state.projects,x.projectId))],["Status",x=>badge(x.status)],["Authorship",x=>`#${E(x.authorOrder)} · ${E(x.coauthors)}`],["Submission",x=>fmt(x.submissionDeadline)],["Review / camera-ready",x=>`${fmt(x.reviewDate)}<div class="subtext">${fmt(x.cameraReady)}</div>`]]),
    sop: () => page("sopDocuments","Application materials","SOP Workspace","Manage master and school-specific SOP versions with structured reusable sections.",[["Document",x=>`<div class="school-name">${E(x.school)}</div><div class="subtext">${E(x.version)} · ${E(x.wordLimit)} words</div>`],["Status",x=>badge(x.status)],["Faculty",x=>E(x.facultyMentions)],["Projects",x=>E(x.projectsUsed)],["Research fit",x=>E(x.researchFit)]]),
    recommendations: () => `${head("Recommendation operations","Recommendation Tracker","Manage recommenders, per-school submissions, materials and reminders.",`<button class="btn" data-ext-add="recommenders">+ Recommender</button><button class="btn primary" data-ext-add="recommendations">+ School request</button>`)}<div class="grid two-col"><section class="panel"><div class="panel-head"><h2>Recommenders</h2><span>${state.recommenders.length}</span></div><div class="panel-body">${state.recommenders.length?state.recommenders.map(x=>`<div class="queue-item"><div class="queue-top"><strong>${E(x.name)}</strong>${badge(x.letterStatus)}</div><p>${E(x.institution)} · ${E(x.relationship)} · ${E(x.strengthEstimate)}</p><button class="btn subtle" data-ext-edit="recommenders:${x.id}">Edit</button></div>`).join(""):`<div class="empty">Add recommenders and relationship evidence.</div>`}</div></section><section class="panel"><div class="panel-head"><h2>School requests</h2><span>${state.recommendations.length}</span></div><div class="panel-body">${state.recommendations.length?state.recommendations.map(x=>`<div class="queue-item"><div class="queue-top"><strong>${E(label(state.recommenders,x.recommenderId))}</strong>${badge(x.submitted?"submitted":"pending")}</div><p>${E(label(state.applications,x.applicationId,"id"))} · due ${fmt(x.deadline)}</p><button class="btn subtle" data-ext-edit="recommendations:${x.id}">Edit</button></div>`).join(""):`<div class="empty">No per-school requests yet.</div>`}</div></section></div>`,
    contact_workspace: () => page("contactRecords","Evidence-based outreach","Cold Email Workspace","Every draft links faculty research, a candidate project and a cited paper.",[["Faculty",x=>`<div class="faculty-name">${E(label(state.faculty,x.facultyId))}</div>`],["Status",x=>badge(x.status)],["Subject",x=>E(x.subject)],["Project",x=>E(label(state.projects,x.relatedProject))],["Research reference",x=>E(x.facultyReference)],["Next action",x=>x.followUpDate?fmt(x.followUpDate):"—"]]),
    tests: () => page("tests","Standardized tests","Test Tracker","Track registrations, section scores, targets and school requirement readiness.",[["Test",x=>`<div class="school-name">${E(x.type)}</div>`],["Date",x=>fmt(x.testDate)],["Total",x=>`<span class="score">${E(x.total||"—")}</span>`],["Sections",x=>`R ${E(x.reading||"—")} · L ${E(x.listening||"—")} · S ${E(x.speaking||"—")} · W ${E(x.writing||"—")}`],["Target",x=>E(x.targetScore)],["Notes",x=>E(x.notes)]]),
    cv: () => page("cvItems","Structured profile","CV Builder Data","Maintain reusable Academic CV and Application CV records.",[["Section",x=>badge(x.section)],["Item",x=>`<div class="school-name">${E(x.title)}</div><div class="subtext">${E(x.organization)}</div>`],["Dates",x=>`${E(x.startDate)} – ${E(x.endDate)}`],["Description",x=>E(x.description)],["Exports",x=>`${x.includeAcademic?"Academic ":""}${x.includeApplication?"Application":""}`]]),
    interviews: () => page("interviews","Results","Interview Tracker","Prepare faculty-specific research conversations and preserve detailed notes.",[["School",x=>E(program(state.applications.find(a=>a.id===x.applicationId)?.programId)?.school)],["Faculty",x=>E(label(state.faculty,x.facultyId))],["Date",x=>fmt(x.date)],["Format",x=>`${E(x.format)} · ${E(x.duration)} min`],["Preparation",x=>E(x.projectPitch)],["Follow-up",x=>E(x.followUp)]]),
    offers: () => page("offers","Decision matrix","Offer Comparison","Preserve raw dimensions and weights before calculating a decision score.",[["Program",x=>E(label(state.programs,x.programId,"school"))],["Advisor",x=>E(x.advisor)],["Research fit",x=>E(x.researchFit)],["Funding / stipend",x=>`${E(x.funding)} · $${money(x.stipend)}`],["Culture / placement",x=>`${E(x.labCulture)} · ${E(x.placement)}`],["Notes",x=>E(x.notes)]]),
    costs: () => { const est=state.costs.reduce((n,x)=>n+Number(x.estimated||0),0),act=state.costs.reduce((n,x)=>n+Number(x.actual||0),0); return `${head("Budget","Application Cost Tracker","Compare estimated and actual application-cycle costs.",`<button class="btn primary" data-ext-add="costs">+ Cost item</button>`)}<div class="grid stats">${stat("Estimated total","$"+money(est),"All categories")}${stat("Actual total","$"+money(act),"Recorded spending")}${stat("Remaining","$"+money(est-act),"Estimate minus actual")}</div>${page("costs","","Cost items","",[["Category",x=>E(x.category)],["Application",x=>E(label(state.applications,x.applicationId,"id"))],["Estimated",x=>`$${money(x.estimated)}`],["Actual",x=>`$${money(x.actual)}`],["Notes",x=>E(x.notes)]]).replace(/^<div class="page-head">[\s\S]*?<\/div><section/,"<section")}`; },
    labnetwork: () => page("labMembers","Lab intelligence","Lab Members & Tsinghua Network","Track current members, alumni, public contacts and potential consultation value.",[["Person",x=>`<div class="faculty-name">${E(x.name)}</div><div class="subtext">${E(x.role)}</div>`],["Faculty",x=>E(label(state.faculty,x.facultyId))],["Education",x=>`${E(x.undergraduateInstitution)}<div class="subtext">${E(x.previousInstitutions)}</div>`],["Tsinghua",x=>badge(x.isTsinghuaAlumni)],["Contact score",x=>`<span class="score">${E(x.contactCandidateScore||0)}</span>`],["Why useful",x=>E(x.whyUseful)]]),
    community: () => page("communityClaims","Evidence, not fact","Community Intelligence","Store anecdotes as claims, preserve uncertainty and triangulate against official sources.",[["Faculty",x=>E(label(state.faculty,x.facultyId))],["Platform",x=>badge(x.sourcePlatform)],["Category",x=>E(x.category)],["Claim",x=>E(x.rawClaim)],["Reliability",x=>badge(x.reliability)],["Verification",x=>badge(x.verification)]]),
    faculty_timeline: () => page("facultyTimeline","Longitudinal evidence","Faculty Evidence Timeline","See how recruiting, research, network and contact judgments evolve.",[["Date",x=>fmt(x.date)],["Faculty",x=>E(label(state.faculty,x.facultyId))],["Type",x=>badge(x.type)],["Detail",x=>E(x.detail)],["Source",x=>x.sourceUrl?`<a href="${E(x.sourceUrl)}" target="_blank">Open ↗</a>`:"—"]]),
    notes: () => page("notes","Quick capture","Research & Admissions Notes","Polymorphic notes with tags for schools, faculty, papers, SOPs and applications.",[["Type",x=>badge(x.entityType)],["Entity",x=>E(x.entityId)],["Note",x=>E(x.body)],["Tags",x=>E(x.tags)],["Created",x=>fmt(x.createdAt)]]),
  };
  window.extendedViews=views;
  window.extendedBind=function(){
    document.querySelectorAll("[data-ext-add]").forEach(x=>x.onclick=()=>openForm(x.dataset.extAdd));
    document.querySelectorAll("[data-ext-edit]").forEach(x=>x.onclick=()=>{const [key,recordId]=x.dataset.extEdit.split(":");openForm(key,recordId)});
  };
})();
