window.SEED_DATA = {
  meta: { version: 1, cycle: "2028 Fall", createdAt: "2026-08-20T00:00:00.000Z" },
  profile: {
    name: "Candidate", institution: "Tsinghua University", department: "Computer Science",
    degree: "B.S.", gpa: 3.3, cycle: "2028 Fall", target: "US CS / AI PhD · Multimodal + Robotics",
    focus: ["Multimodal AI", "Robotics / Embodied AI", "Video & Spatial Reasoning", "Benchmark & Data"],
    statement: "Build reliable multimodal reasoning systems that track latent human state, perspective, and causality over time."
  },
  projects: [
    { id:"p1", name:"EmoTree-Bench", short:"EmoTree", status:"active", area:"Longitudinal Emotion Reasoning", problem:"Can models track latent emotional states across branching interaction histories?", method:"Tree/DAG histories, counterfactual choices, causal evidence grounding, text and talking-head modalities.", contribution:"Benchmark design, task formulation, data pipeline and evaluation.", keywords:["emotion reasoning","affective computing","multimodal LLM","social reasoning","longitudinal reasoning","counterfactual reasoning","benchmark","emotion understanding","interactive agents"], updated:"2026-08-20" },
    { id:"p2", name:"LIMO4SI / Ego-Exo Spatial Reasoning", short:"LIMO4SI", status:"experiment", area:"Video QA & Multimodal Spatial Reasoning", problem:"Can models align ego/exo perspectives to reason about space, gaze, visibility and intent?", method:"Ego-Exo4D Video QA with perspective, temporal and gaze grounding.", contribution:"Benchmark construction, annotation strategy and evaluation design.", keywords:["video QA","multimodal reasoning","ego-exo","egocentric vision","spatial reasoning","perspective grounding","gaze","human-object interaction","temporal grounding","human intent","benchmark"], updated:"2026-08-20" }
  ],
  programs: [
    { id:"pr1", school:"Stanford University", department:"Computer Science", program:"Computer Science PhD", city:"Stanford", state:"CA", tier:"Dream", deadline:"2027-12-05", fee:125, gre:"Not required", toefl:"100", funding:"Fully funded", model:"Committee / faculty match", facultyCount:3, priority:96, status:"Shortlisted", sourceId:"s1" },
    { id:"pr2", school:"Massachusetts Institute of Technology", department:"EECS", program:"EECS PhD", city:"Cambridge", state:"MA", tier:"Dream", deadline:"2027-12-01", fee:90, gre:"Not accepted", toefl:"100", funding:"Fully funded", model:"Department admission", facultyCount:2, priority:94, status:"Researching", sourceId:"s2" },
    { id:"pr3", school:"Carnegie Mellon University", department:"School of Computer Science", program:"Computer Science PhD", city:"Pittsburgh", state:"PA", tier:"Reach", deadline:"2027-12-10", fee:100, gre:"Optional", toefl:"100", funding:"Fully funded", model:"Program-based", facultyCount:2, priority:92, status:"Shortlisted", sourceId:"s3" },
    { id:"pr4", school:"University of Washington", department:"Paul G. Allen School", program:"Computer Science & Engineering PhD", city:"Seattle", state:"WA", tier:"Target", deadline:"2027-12-15", fee:85, gre:"Not required", toefl:"92", funding:"Fully funded", model:"Committee-based", facultyCount:2, priority:88, status:"Researching", sourceId:"s4" },
    { id:"pr5", school:"University of Michigan", department:"CSE", program:"Computer Science and Engineering PhD", city:"Ann Arbor", state:"MI", tier:"Target", deadline:"2027-12-15", fee:90, gre:"Optional", toefl:"100", funding:"Fully funded", model:"Mixed", facultyCount:1, priority:82, status:"Considering", sourceId:"s5" }
  ],
  faculty: [
    {id:"f1",name:"Fei-Fei Li",programId:"pr1",position:"Professor",interests:["computer vision","multimodal intelligence","human-centered AI"],recruiting:"unknown",consideration:"high_priority",contact:"not_planned",completion:76,tsinghua:1,lastChecked:"2026-08-15",email:"",website:"https://profiles.stanford.edu/fei-fei-li",why:"Human-centered visual intelligence and multimodal perception.",concerns:"Recruiting status needs official confirmation."},
    {id:"f2",name:"Jiajun Wu",programId:"pr1",position:"Associate Professor",interests:["3D vision","physical reasoning","embodied AI","video"],recruiting:"likely_recruiting",consideration:"considering",contact:"planning",completion:68,tsinghua:0,lastChecked:"2026-08-12",email:"",website:"https://jiajunwu.com/",why:"Strong spatial and physical reasoning connection to LIMO4SI.",concerns:"Validate direct ego-exo overlap."},
    {id:"f3",name:"Diyi Yang",programId:"pr1",position:"Assistant Professor",interests:["NLP","social intelligence","human-centered AI","LLM"],recruiting:"unknown",consideration:"considering",contact:"not_planned",completion:61,tsinghua:0,lastChecked:"2026-08-10",email:"",website:"https://cs.stanford.edu/~diyiy/",why:"Social reasoning offers a bridge to EmoTree.",concerns:"Multimodal focus needs review."},
    {id:"f4",name:"Antonio Torralba",programId:"pr2",position:"Professor",interests:["computer vision","scene understanding","multimodal learning"],recruiting:"unknown",consideration:"considering",contact:"not_planned",completion:57,tsinghua:0,lastChecked:"2026-07-28",email:"",website:"https://people.csail.mit.edu/torralba/",why:"Broad visual reasoning and scene understanding.",concerns:"Information needs refresh."},
    {id:"f5",name:"Phillip Isola",programId:"pr2",position:"Associate Professor",interests:["visual intelligence","representation learning","generative models"],recruiting:"unknown",consideration:"researching",contact:"not_planned",completion:49,tsinghua:0,lastChecked:"2026-08-01",email:"",website:"https://web.mit.edu/phillipi/",why:"Visual representation learning may support benchmark methods.",concerns:"Research fit still broad."},
    {id:"f6",name:"Deva Ramanan",programId:"pr3",position:"Professor",interests:["computer vision","video understanding","embodied perception"],recruiting:"likely_recruiting",consideration:"high_priority",contact:"planning",completion:81,tsinghua:1,lastChecked:"2026-08-17",email:"",website:"https://www.cs.cmu.edu/~deva/",why:"Video understanding and embodied perception strongly connect to LIMO4SI.",concerns:"Confirm 2028 capacity."},
    {id:"f7",name:"Louis-Philippe Morency",programId:"pr3",position:"Professor",interests:["multimodal machine learning","affective computing","social intelligence"],recruiting:"unknown",consideration:"high_priority",contact:"drafted",completion:86,tsinghua:0,lastChecked:"2026-08-18",email:"",website:"https://www.cs.cmu.edu/~morency/",why:"Direct overlap with multimodal affect and social reasoning for EmoTree.",concerns:"Recruiting not yet confirmed."},
    {id:"f8",name:"Ali Farhadi",programId:"pr4",position:"Professor",interests:["computer vision","vision-language","embodied AI"],recruiting:"unknown",consideration:"considering",contact:"not_planned",completion:54,tsinghua:0,lastChecked:"2026-07-20",email:"",website:"https://homes.cs.washington.edu/~ali/",why:"Vision-language and embodied AI complement LIMO4SI.",concerns:"Last checked over one month ago."},
    {id:"f9",name:"Yejin Choi",programId:"pr4",position:"Professor",interests:["NLP","commonsense reasoning","social intelligence","LLM"],recruiting:"unknown",consideration:"high_priority",contact:"planning",completion:73,tsinghua:1,lastChecked:"2026-08-13",email:"",website:"https://homes.cs.washington.edu/~yejin/",why:"Social and commonsense reasoning strongly supports EmoTree framing.",concerns:"Confirm advising arrangement and multimodal direction."},
    {id:"f10",name:"Andrew Owens",programId:"pr5",position:"Assistant Professor",interests:["multimodal learning","audio-visual learning","computer vision","video"],recruiting:"likely_recruiting",consideration:"backup",contact:"not_planned",completion:66,tsinghua:0,lastChecked:"2026-08-09",email:"",website:"https://andrewowens.com/",why:"Multimodal video work is relevant to both projects.",concerns:"Only one currently tracked matching faculty at the program."}
  ],
  matches: [
    {facultyId:"f1",projectId:"p1",score:88,topic:90,method:82,data:90,multimodal:94,llm:80,recent:84,collaboration:87,explanation:"Human-centered multimodal intelligence aligns with longitudinal emotion understanding; benchmark framing is a strong bridge.",pitch:"Connect human-centered visual intelligence with controlled, history-sensitive emotion evaluation."},
    {facultyId:"f1",projectId:"p2",score:84,topic:86,method:80,data:88,multimodal:95,llm:72,recent:82,collaboration:85,explanation:"Visual intelligence and human-centered perception support cross-view spatial reasoning.",pitch:"Extend human-centered perception evaluation to aligned ego/exo video."},
    {facultyId:"f2",projectId:"p1",score:63,topic:55,method:72,data:70,multimodal:72,llm:58,recent:67,collaboration:62,explanation:"Method overlap in structured reasoning, but limited direct affective focus.",pitch:"Use structured world reasoning for branching social histories."},
    {facultyId:"f2",projectId:"p2",score:93,topic:94,method:94,data:88,multimodal:92,llm:78,recent:95,collaboration:96,explanation:"3D, physical and embodied reasoning are a direct match for cross-view spatial and intent reasoning.",pitch:"Build cross-view benchmarks connecting geometry, visibility and human intent."},
    {facultyId:"f3",projectId:"p1",score:91,topic:96,method:85,data:88,multimodal:76,llm:94,recent:92,collaboration:93,explanation:"Social intelligence and LLM reasoning strongly match EmoTree's history-sensitive human state modeling.",pitch:"Evaluate whether social LLMs maintain consistent latent emotion models across counterfactual histories."},
    {facultyId:"f3",projectId:"p2",score:54,topic:51,method:58,data:60,multimodal:49,llm:66,recent:55,collaboration:48,explanation:"Some human-intent overlap, but video and spatial grounding are not central.",pitch:"Study language-grounded explanations of spatial intent."},
    {facultyId:"f4",projectId:"p1",score:64,topic:54,method:70,data:76,multimodal:80,llm:56,recent:68,collaboration:62,explanation:"Strong visual benchmark expertise with weaker direct affective overlap.",pitch:"Introduce history-sensitive social states into visual scene understanding."},
    {facultyId:"f4",projectId:"p2",score:91,topic:92,method:90,data:94,multimodal:91,llm:70,recent:90,collaboration:92,explanation:"Scene and visual understanding provide strong foundations for ego-exo correspondence.",pitch:"Evaluate viewpoint-grounded scene understanding in synchronized ego/exo video."},
    {facultyId:"f5",projectId:"p1",score:59,topic:48,method:69,data:67,multimodal:76,llm:55,recent:62,collaboration:57,explanation:"General visual learning methods may transfer, but social affect is indirect.",pitch:"Learn history-aware visual representations for latent social state."},
    {facultyId:"f5",projectId:"p2",score:82,topic:79,method:86,data:82,multimodal:87,llm:65,recent:84,collaboration:83,explanation:"Visual representation learning and generative modeling support cross-view grounding.",pitch:"Learn aligned representations across first- and third-person observations."},
    {facultyId:"f6",projectId:"p1",score:58,topic:45,method:67,data:73,multimodal:75,llm:49,recent:66,collaboration:57,explanation:"Video methods transfer, though emotion is not a core focus.",pitch:"Ground latent social state in observable video evidence."},
    {facultyId:"f6",projectId:"p2",score:95,topic:96,method:94,data:96,multimodal:92,llm:72,recent:96,collaboration:97,explanation:"Video understanding and embodied perception directly align with ego-exo spatial reasoning and benchmark construction.",pitch:"Create diagnostic cross-view video tasks for visibility, gaze and intent."},
    {facultyId:"f7",projectId:"p1",score:97,topic:99,method:94,data:96,multimodal:98,llm:89,recent:97,collaboration:98,explanation:"Multimodal affective computing and social intelligence are a near-direct match for EmoTree.",pitch:"Extend multimodal affect modeling from moment-level signals to causal, branching interaction histories."},
    {facultyId:"f7",projectId:"p2",score:66,topic:60,method:72,data:74,multimodal:86,llm:58,recent:69,collaboration:64,explanation:"Strong multimodal methods but less direct spatial and ego-exo focus.",pitch:"Model human intent by combining gaze, perspective and multimodal behavior."},
    {facultyId:"f8",projectId:"p1",score:62,topic:50,method:68,data:72,multimodal:78,llm:65,recent:64,collaboration:60,explanation:"Vision-language methods overlap; longitudinal affect is indirect.",pitch:"Ground social-state reasoning in vision-language evidence."},
    {facultyId:"f8",projectId:"p2",score:90,topic:89,method:91,data:88,multimodal:94,llm:79,recent:91,collaboration:92,explanation:"Vision-language and embodied AI connect strongly to perspective and intent grounding.",pitch:"Diagnose embodied vision-language models through synchronized cross-view QA."},
    {facultyId:"f9",projectId:"p1",score:96,topic:98,method:92,data:91,multimodal:84,llm:98,recent:97,collaboration:98,explanation:"Commonsense and social intelligence provide a strong conceptual match to longitudinal emotional reasoning.",pitch:"Test whether commonsense models maintain causal social state across divergent histories."},
    {facultyId:"f9",projectId:"p2",score:65,topic:62,method:69,data:67,multimodal:61,llm:80,recent:66,collaboration:63,explanation:"Intent and reasoning overlap, while video grounding is secondary.",pitch:"Explain cross-view human intent with grounded commonsense inference."},
    {facultyId:"f10",projectId:"p1",score:75,topic:68,method:80,data:83,multimodal:92,llm:61,recent:79,collaboration:74,explanation:"Multimodal temporal methods could support talking-head EmoTree extension.",pitch:"Track emotion through synchronized audiovisual cues over long interactions."},
    {facultyId:"f10",projectId:"p2",score:88,topic:85,method:90,data:91,multimodal:96,llm:64,recent:90,collaboration:87,explanation:"Multimodal video research aligns with temporal and cross-view benchmark design.",pitch:"Use multimodal signals to resolve occlusion and intent across viewpoints."}
  ],
  applications: [
    {id:"a1",programId:"pr1",status:"Preparing",deadline:"2027-12-05",progress:36,tasks:["Program researched","Faculty researched","SOP draft"],notes:"Prioritize faculty triangulation."},
    {id:"a2",programId:"pr3",status:"Shortlisted",deadline:"2027-12-10",progress:24,tasks:["Program researched","Faculty shortlist complete"],notes:"Strong two-project coverage."},
    {id:"a3",programId:"pr4",status:"Researching",deadline:"2027-12-15",progress:16,tasks:["Program researched"],notes:"Verify advising availability."}
  ],
  tasks: [
    {id:"t1",title:"Review 3 recent papers from Morency lab",due:"2026-08-27",type:"Paper",done:false},
    {id:"t2",title:"Verify CMU faculty recruiting status",due:"2026-09-02",type:"Faculty",done:false},
    {id:"t3",title:"Draft candidate research narrative",due:"2026-09-08",type:"SOP",done:false},
    {id:"t4",title:"Export monthly backup",due:"2026-09-20",type:"Data",done:false}
  ],
  sources: [
    {id:"s1",entity:"Stanford CS PhD",name:"Department website",url:"https://www.cs.stanford.edu/admissions/phd-admissions",type:"official_department",lastChecked:"2026-08-10",confidence:"high",status:"outdated",claim:"Deadline and requirements placeholder; verify for 2028 cycle."},
    {id:"s2",entity:"MIT EECS PhD",name:"EECS admissions",url:"https://www.eecs.mit.edu/academics/graduate-programs/admission-process/",type:"official_department",lastChecked:"2026-08-10",confidence:"high",status:"outdated",claim:"Cycle-specific deadline must be rechecked."},
    {id:"s3",entity:"CMU SCS PhD",name:"SCS doctoral admissions",url:"https://www.cs.cmu.edu/academics/doctoral/admissions",type:"official_department",lastChecked:"2026-08-11",confidence:"high",status:"outdated",claim:"Example requirements; not confirmed for 2028."},
    {id:"s4",entity:"UW Allen School PhD",name:"Allen School admissions",url:"https://www.cs.washington.edu/academics/phd/admissions",type:"official_department",lastChecked:"2026-08-09",confidence:"high",status:"outdated",claim:"Example data pending cycle confirmation."},
    {id:"s5",entity:"Michigan CSE PhD",name:"CSE graduate admissions",url:"https://cse.engin.umich.edu/academics/graduate/admissions/",type:"official_department",lastChecked:"2026-08-08",confidence:"high",status:"outdated",claim:"Example data pending cycle confirmation."}
  ],
  notes: [],
  history: [{id:"h1",at:"2026-08-20T00:00:00.000Z",action:"System initialized",entity:"Workspace",detail:"Loaded curated demonstration dataset"}]
};
