/* Optional UI regression: node tests/planning_browser.cjs (server on port 8080). */
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({headless: true});
  const context = await browser.newContext({viewport:{width:1440,height:1000}, timezoneId:'Asia/Shanghai'});
  const page = await context.newPage();
  const errors=[];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:8080', {waitUntil:'domcontentloaded'});
  await page.locator('[data-plan-view="roadmap"]').click();
  assert.equal(await page.locator('.milestone').count(),16);
  await page.locator('[data-milestone-done]').first().check();
  await page.reload({waitUntil:'domcontentloaded'});
  await page.locator('[data-plan-view="roadmap"]').click();
  assert.equal(await page.locator('[data-milestone-done]').first().isChecked(),true);
  await page.locator('[data-milestone-edit]').first().click();
  await page.locator('input[name="due"]').fill('2026-10-10');
  await page.locator('textarea[name="notes"]').fill('User-authored plan note');
  await page.locator('button', {hasText:'Save changes'}).click();
  assert.equal(await page.evaluate(()=>state.milestones[0].due),'2026-10-10');
  await page.locator('#add-milestone').click();
  await page.locator('input[name="title"]').fill('My custom research checkpoint');
  await page.locator('button', {hasText:'Save changes'}).click();
  assert.equal(await page.locator('.milestone').count(),17);
  await page.screenshot({path:'/tmp/application-roadmap-desktop.png', fullPage:true});
  await page.evaluate(()=>{state.recommenders.push({id:'browser-ref', name:'Test recommender',letterStatus:'not_discussed'});persist();currentView='recommendations';shell();});
  await page.locator('[data-plan-letter]').first().click();
  assert.equal(await page.evaluate(()=>state.recommendations.length),1);
  await page.locator('.recommendation-matrix [data-ext-edit]').first().click();
  await page.locator('input[name="requested"]').check();
  await page.locator('input[name="deadline"]').fill('2027-12-01');
  await page.locator('.modal-foot button', {hasText:/^Save$/}).click();
  assert.equal(await page.locator('.recommendation-matrix button', {hasText:'已邀请'}).count(),1);
  await page.locator('[data-letter-count]').first().fill('3');
  await page.locator('[data-letter-count]').first().press('Tab');
  assert.equal(await page.evaluate(()=>state.applications[0].requiredLetters),3);
  // Full JSON export must generate one download, not the old extra CSV.
  await page.locator('[data-view="settings"]').click();
  const downloads=[];page.on('download', d=>downloads.push(d.suggestedFilename()));
  const downloadEvent=page.waitForEvent('download');
  await page.locator('#export-settings').click();await downloadEvent;
  await page.waitForTimeout(200);
  assert.equal(downloads.length,1);assert.match(downloads[0],/\.json$/);
  const backup=await page.evaluate(()=>JSON.stringify(state));
  await page.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(backup)});
  assert.equal(await page.evaluate(()=>state.milestones.length),17);
  assert.equal(await page.evaluate(()=>state.milestones[0].notes),'User-authored plan note');
  // Positive UTC offsets must place dates on their local calendar day.
  await page.evaluate(()=>{state.milestones.push({id:'timezone',phase:'foundation',title:'TIMEZONE_SENTINEL',due:'2026-10-10',done:false});window.calendarMonth='2026-10';currentView='calendar';shell();});
  assert.equal(await page.locator('.day').filter({has:page.locator('.event', {hasText:'TIMEZONE_SENTINEL'})}).locator('.day-num').textContent(),'10');
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>{currentView='roadmap';shell();});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth),true);
  await page.screenshot({path:'/tmp/application-roadmap-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('Browser checks passed: edit, complete, reload, recommendation matrix, JSON round trip, calendar timezone, mobile layout.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
